### ISSUE TITLE
recomendation for number

### ISSUE THREAD

**Issue by satrianivzla** [furkankahvecii/coronavirus-tracker#1]
Excellent work, this 2nd version is way better than the 1st  then just as a small recommendation, you can use PHP number format to show it better for example number_format($result['cases'])
Cheers

**Comment by furkankahvecii** [comment]
Thank you for your suggestion, I added the number_format method. Do you have any other suggestions?

**Comment by furkankahvecii** [comment]
Thank you for your suggestion, I added the number_format method. Do you have any other suggestions?

**Comment by furkankahvecii** [comment]
> Excellent work, this 2nd version is way better than the 1st then just as a small recommendation, you can use PHP number format to show it better for example number_format($result['cases'])
> Cheers

Thank you for your suggestion, I added the number_format method. Do you have any other suggestions?

**Comment by NuggaN85** [comment]
I've got a problem, I only have 404 errors.[https://tchatland.fr/covid19/](url)

**Comment by furkankahvecii** [comment]
> I've got a problem, I only have 404 errors.[https://tchatland.fr/covid19/](url)

I don't really understand, can you explain your problem in more detail ?

**Comment by NuggaN85** [comment]
> > I've got a problem, I only have 404 errors.[https://tchatland.fr/covid19/](url)
> 
> I don't really understand, can you explain your problem in more detail ?

when you're on my site right click on inspect the elements and you'll see that from the 404 no way to fix this problem I don't know where it comes from sorry we can't put Screenshots in attachment

**Comment by furkankahvecii** [comment]
> https://tchatland.fr/covid19/


You get such an error because the urls of the images of the countries are written incorrectly. I'm getting this error too. For example, there is no picture of the Diamond Princess country on page 2 in the table, that's why the mistake.

For the solution of this error;

https://google.org/crisisresponse/covid19-map , you have to look at the pictures in the network section in developer mode and match them with the ones there.

Example = https://www.gstatic.com/onebox/sports/logos/flags/france_icon_square.svg

**Comment by furkankahvecii** [comment]
> > > I've got a problem, I only have 404 errors.[https://tchatland.fr/covid19/](url)
> > 
> > 
> > I don't really understand, can you explain your problem in more detail ?
> 
> when you're on my site right click on inspect the elements and you'll see that from the 404 no way to fix this problem I don't know where it comes from sorry we can't put Screenshots in attachment

You get such an error because the urls of the images of the countries are written incorrectly. I'm getting this error too. For example, there is no picture of the Diamond Princess country on page 2 in the table, that's why the mistake.

For the solution of this error;

https://google.org/crisisresponse/covid19-map , you have to look at the pictures in the network section in developer mode and match them with the ones there.

Example = https://www.gstatic.com/onebox/sports/logos/flags/france_icon_square.svg

**Comment by NuggaN85** [comment]
> > > > I've got a problem, I only have 404 errors.[https://tchatland.fr/covid19/](url)
> > > 
> > > 
> > > I don't really understand, can you explain your problem in more detail ?
> > 
> > 
> > when you're on my site right click on inspect the elements and you'll see that from the 404 no way to fix this problem I don't know where it comes from sorry we can't put Screenshots in attachment
> 
> You get such an error because the urls of the images of the countries are written incorrectly. I'm getting this error too. For example, there is no picture of the Diamond Princess country on page 2 in the table, that's why the mistake.
> 
> For the solution of this error;
> 
> https://google.org/crisisresponse/covid19-map , you have to look at the pictures in the network section in developer mode and match them with the ones there.
> 
> Example = https://www.gstatic.com/onebox/sports/logos/flags/france_icon_square.svg

All right, and the pictures, where do I put them, or exactly?

**Comment by furkankahvecii** [comment]
> > > > > I've got a problem, I only have 404 errors.[https://tchatland.fr/covid19/](url)
> > > > 
> > > > 
> > > > I don't really understand, can you explain your problem in more detail ?
> > > 
> > > 
> > > when you're on my site right click on inspect the elements and you'll see that from the 404 no way to fix this problem I don't know where it comes from sorry we can't put Screenshots in attachment
> > 
> > 
> > You get such an error because the urls of the images of the countries are written incorrectly. I'm getting this error too. For example, there is no picture of the Diamond Princess country on page 2 in the table, that's why the mistake.
> > For the solution of this error;
> > https://google.org/crisisresponse/covid19-map , you have to look at the pictures in the network section in developer mode and match them with the ones there.
> > Example = https://www.gstatic.com/onebox/sports/logos/flags/france_icon_square.svg
> 
> All right, and the pictures, where do I put them, or exactly?

You should be add Controllers->CoronaVirus.php->img_url array .

**Comment by NuggaN85** [comment]
> > > > > > I've got a problem, I only have 404 errors.[https://tchatland.fr/covid19/](url)
> > > > > 
> > > > > 
> > > > > I don't really understand, can you explain your problem in more detail ?
> > > > 
> > > > 
> > > > when you're on my site right click on inspect the elements and you'll see that from the 404 no way to fix this problem I don't know where it comes from sorry we can't put Screenshots in attachment
> > > 
> > > 
> > > You get such an error because the urls of the images of the countries are written incorrectly. I'm getting this error too. For example, there is no picture of the Diamond Princess country on page 2 in the table, that's why the mistake.
> > > For the solution of this error;
> > > https://google.org/crisisresponse/covid19-map , you have to look at the pictures in the network section in developer mode and match them with the ones there.
> > > Example = https://www.gstatic.com/onebox/sports/logos/flags/france_icon_square.svg
> > 
> > 
> > All right, and the pictures, where do I put them, or exactly?
> 
> You should be add Controllers->CoronaVirus.php->img_url array .

ok thanks for this support :)

**Comment by satrianivzla** [comment]
You updated a few your code, the flag issue was fix and everything is ok for me.
I just added 4 things:
2top JS from  http://www.mattvarone.com/web-design/uitotop-jquery-plugin/
Footer section with copyright and your name with link to this repository 
to the flags added basic alt and title with the country name from array  
and finally datatable pagination on top and on bottom updating the JS with
`        $(document).ready(function () {
            $('table').DataTable({
                order: [],
                paging: true,
		"pagingType": "full_numbers",
		"dom": '<"top"flp>rt<"bottom"ip><"clear">',				
                "pageLength": 25,
            });
        });`

**Comment by satrianivzla** [comment]
All these flags failed in local and remote server

Diamond Princess 
Faeroe Islands
Réunion
DRC
Channel Islands
Saint Martin
Isle of Man
Macao
St. Barth
Cabo Verde
Curaçao
Eswatini
St. Vincent Grenadines
Saint Kitts and Nevis
British Virgin Islands
MS Zaandam
Saint Lucia
CAR
Sint Maarten
Congo
Timor-Leste

**Comment by furkankahvecii** [comment]
> You updated a few your code, the flag issue was fix and everything is ok for me.
> I just added 4 things:
> 2top JS from http://www.mattvarone.com/web-design/uitotop-jquery-plugin/
> Footer section with copyright and your name with link to this repository
> to the flags added basic alt and title with the country name from array
> and finally datatable pagination on top and on bottom updating the JS with
> ` $(document).ready(function () { $('table').DataTable({ order: [], paging: true, "pagingType": "full_numbers", "dom": '<"top"flp>rt<"bottom"ip><"clear">', "pageLength": 25, }); });`

Datatable updated, thank you.

**Comment by furkankahvecii** [comment]
> All these flags failed in local and remote server
> 
> Diamond Princess
> Faeroe Islands
> Réunion
> DRC
> Channel Islands
> Saint Martin
> Isle of Man
> Macao
> St. Barth
> Cabo Verde
> Curaçao
> Eswatini
> St. Vincent Grenadines
> Saint Kitts and Nevis
> British Virgin Islands
> MS Zaandam
> Saint Lucia
> CAR
> Sint Maarten
> Congo
> Timor-Leste

I have updated some countries but I really couldn't find what I couldn't update. I think it won't be a problem :)

**Comment by satrianivzla** [comment]
cool just need to update now only a few 
St. Vincent Grenadines
MS Zaandam
Saint Kitts and Nevis
Guinea-Bissau
British Virgin Islands
CAR
Saint Lucia
St. Barth
Sint Maarten

**Comment by satrianivzla** [comment]
I wasn't able to add **Recovered cases** to the **drawRegionsMap** function, it show me the data array but gave me an error 'Incompatible data table: Error: Table contains more columns than expected (Expecting 3 columns)'
            var data = google.visualization.arrayToDataTable([
                ['Country', 'Confirmed Cases',  'Total Deaths', 'Recovered Cases',  ], <?php foreach($RESULT_DATA as $result) {
                    echo '["'.$result['country'].
                    '",' .$result['cases']. 
		    ','  .$result['deaths'].
		    ','  .$result['recovered'].  					
                    '], ';

**Comment by satrianivzla** [comment]
and well you can add a preloader like this one 
https://ihatetomatoes.net/create-css3-spinning-preloader/

**Comment by furkankahvecii** [comment]
> cool just need to update now only a few
> St. Vincent Grenadines
> MS Zaandam
> Saint Kitts and Nevis
> Guinea-Bissau
> British Virgin Islands
> CAR
> Saint Lucia
> St. Barth
> Sint Maarten

no problem, added.

**Comment by furkankahvecii** [comment]
> I wasn't able to add **Recovered cases** to the **drawRegionsMap** function, it show me the data array but gave me an error 'Incompatible data table: Error: Table contains more columns than expected (Expecting 3 columns)'
> var data = google.visualization.arrayToDataTable([
> ['Country', 'Confirmed Cases', 'Total Deaths', 'Recovered Cases', ], <?php foreach($RESULT_DATA as $result) {
> echo '["'.$result['country'].
> '",' .$result['cases'].
> ',' .$result['deaths'].
> ',' .$result['recovered'].
> '], ';

Not necessary, this is fine 👍
